language: node_js
node_js:
    - "stable"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install
    - bower install
after_success:
    cat coverage/report-lcov/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

